run-dist:
    ./build/install/app/bin/app:

run:
	./gradlew run

lint:
	./gradlew checkstyleMain

build:
	./gradlew clean build

report:
	./gradlew jacocoTestReport

test:
	./gradlew test

.PHONY: build
